name: Java CI with Gradle

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout reposistory
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: change branch of the core
      run: cd salesforce-core && git checkout develop && git pull && cd ..

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble the project
      run: ./gradlew assemble

    - name: Build with Gradle
      run: ./gradlew check -PskipReports

    - name: Style Code Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: CheckStyle
        path: build/reports/checkstyle/

